#ifndef PAKE_CONSTANTS_H
#define PAKE_CONSTANTS_H

#define PAKE_SYM_KEY_SIZE 64  // SHA512_DIGEST_LENGTH
#define PAKE_CT_SIZE 1568     // PQCLEAN_KYBER1024_CLEAN_CRYPTO_CIPHERTEXTBYTES
#define PAKE_PK_SIZE 1568     // PQCLEAN_KYBER1024_CLEAN_CRYPTO_PUBLICKEYBYTES
#define PAKE_SK_SIZE 3168     // PQCLEAN_KYBER1024_CLEAN_CRYPTO_SECRETKEYBYTES
#define PAKE_EPK_SIZE 1530
#define PAKE_ECT_SIZE PAKE_CT_SIZE
#define PAKE_SHARED_SECRET_SIZE 32  // SHA256_DIGEST_LENGTH

#endif  // PAKE_CONSTANTS_H
