#ifndef PQPAKE_CONSTANTS_H
#define PQPAKE_CONSTANTS_H

#define PQPAKE_SYM_KEY_SIZE 64  // SHA512_DIGEST_LENGTH
#define PQPAKE_CT_SIZE 1568  // PQCLEAN_KYBER1024_CLEAN_CRYPTO_CIPHERTEXTBYTES
#define PQPAKE_PK_SIZE 1568  // PQCLEAN_KYBER1024_CLEAN_CRYPTO_PUBLICKEYBYTES
#define PQPAKE_SK_SIZE 3168  // PQCLEAN_KYBER1024_CLEAN_CRYPTO_SECRETKEYBYTES
#define PQPAKE_EPK_SIZE 1530
#define PQPAKE_ECT_SIZE PQPAKE_CT_SIZE
#define PQPAKE_SHARED_SECRET_SIZE 32  // SHA256_DIGEST_LENGTH

#endif  // PQPAKE_CONSTANTS_H
